class EntityManager {
    monsterDb = [];
    chestDb = [];
    neutralDb = [];
    npcDb = [];

    init() {

        //monsters

        this.monsterDb.push(new Entity);
        this.monsterDb[0].type = 'monster';
        this.monsterDb[0].behavior = 'scared';
        this.monsterDb[0].name = 'Goblin';
        this.monsterDb[0].cssClass = 'monster-goblin';
        this.monsterDb[0].stats.maxhp = 4;
        this.monsterDb[0].stats.baseDmg = 2;
        this.monsterDb[0].stats.armor = 2;
        this.monsterDb[0].stats.evasion = 3;
        this.monsterDb[0].stats.effectsImmunity = 0;
        this.monsterDb[0].stats.piercing = 1;
        this.monsterDb[0].stats.critPower = 1.2;
        this.monsterDb[0].stats.critChance = 3;
        this.monsterDb[0].stats.burnDmg = 0;
        this.monsterDb[0].stats.poisonDmg = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[1].type = 'monster';
        this.monsterDb[1].behavior = 'aggressive';
        this.monsterDb[1].name = 'Cave snake';
        this.monsterDb[1].cssClass = 'monster-snake';
        this.monsterDb[1].stats.maxhp = 16;
        this.monsterDb[1].stats.baseDmg = 2;
        this.monsterDb[1].stats.armor = 2;
        this.monsterDb[1].stats.piercing = 1;
        this.monsterDb[1].stats.critPower = 1.5;
        this.monsterDb[1].stats.critChance = 5;
        this.monsterDb[1].stats.burnDmg = 0;
        this.monsterDb[1].stats.poisonDmg = 2;

        this.monsterDb.push(new Entity);
        this.monsterDb[2].type = 'monster';
        this.monsterDb[2].behavior = 'aggressive';
        this.monsterDb[2].name = 'Orc warrior';
        this.monsterDb[2].cssClass = 'monster-orc';
        this.monsterDb[2].stats.maxhp = 242;
        this.monsterDb[2].stats.baseDmg = 54;
        this.monsterDb[2].stats.armor = 22;
        this.monsterDb[2].stats.piercing = 2;
        this.monsterDb[2].stats.critPower = 1.8;
        this.monsterDb[2].stats.critChance = 6;
        this.monsterDb[2].stats.burnDmg = 0;
        this.monsterDb[2].stats.poisonDmg = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[3].type = 'monster';
        this.monsterDb[3].behavior = 'scared';
        this.monsterDb[3].name = 'Orc shaman';
        this.monsterDb[3].cssClass = 'monster-orc-shaman';
        this.monsterDb[3].stats.maxhp = 848;
        this.monsterDb[3].stats.baseDmg = 75;
        this.monsterDb[3].stats.armor = 32;
        this.monsterDb[3].stats.effectsImmunity = 2;
        this.monsterDb[3].stats.piercing = 23;
        this.monsterDb[3].stats.critPower = 2;
        this.monsterDb[3].stats.critChance = 8;
        this.monsterDb[3].stats.burnDmg = 2;
        this.monsterDb[3].stats.poisonDmg = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[4].type = 'monster';
        this.monsterDb[4].behavior = 'aggressive';
        this.monsterDb[4].name = 'Orc alpha';
        this.monsterDb[4].cssClass = 'monster-orc-alpha';
        this.monsterDb[4].stats.maxhp = 927;
        this.monsterDb[4].stats.baseDmg = 127;
        this.monsterDb[4].stats.armor = 54;
        this.monsterDb[4].stats.effectsImmunity = 1;
        this.monsterDb[4].stats.piercing = 25;
        this.monsterDb[4].stats.critPower = 2;
        this.monsterDb[4].stats.critChance = 5;
        this.monsterDb[4].stats.burnDmg = 0;
        this.monsterDb[4].stats.poisonDmg = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[5].type = 'monster';
        this.monsterDb[5].behavior = 'aggressive';
        this.monsterDb[5].name = 'Vampire';
        this.monsterDb[5].cssClass = 'monster-vampire';
        this.monsterDb[5].stats.maxhp = 1260;
        this.monsterDb[5].stats.baseDmg = 27;
        this.monsterDb[5].stats.armor = 5;
        this.monsterDb[5].stats.effectsImmunity = 3;
        this.monsterDb[5].stats.piercing = 2;
        this.monsterDb[5].stats.critPower = 4;
        this.monsterDb[5].stats.critChance = 15;
        this.monsterDb[5].stats.burnDmg = 2;
        this.monsterDb[5].stats.poisonDmg = 2;

        this.monsterDb.push(new Entity);
        this.monsterDb[6].type = 'monster';
        this.monsterDb[6].behavior = 'scared';
        this.monsterDb[6].name = 'Undead wizard';
        this.monsterDb[6].cssClass = 'monster-undead-wizard';
        this.monsterDb[6].stats.maxhp = 2395;
        this.monsterDb[6].stats.baseDmg = 45;
        this.monsterDb[6].stats.armor = 4;
        this.monsterDb[6].stats.effectsImmunity = 4;
        this.monsterDb[6].stats.piercing = 8;
        this.monsterDb[6].stats.critPower = 2;
        this.monsterDb[6].stats.critChance = 7;
        this.monsterDb[6].stats.burnDmg = 4;
        this.monsterDb[6].stats.poisonDmg = 3;
        this.monsterDb[6].stats.blindChance = 5;
        this.monsterDb[6].stats.blindPower = 5;

        this.monsterDb.push(new Entity);
        this.monsterDb[7].type = 'monster';
        this.monsterDb[7].behavior = 'aggressive';
        this.monsterDb[7].name = 'Undead legionist';
        this.monsterDb[7].cssClass = 'monster-undead-legionist';
        this.monsterDb[7].stats.maxhp = 4532;
        this.monsterDb[7].stats.baseDmg = 47;
        this.monsterDb[7].stats.armor = 15;
        this.monsterDb[7].stats.effectsImmunity = 1;
        this.monsterDb[7].stats.piercing = 8;
        this.monsterDb[7].stats.critPower = 5;
        this.monsterDb[7].stats.critChance = 2;
        this.monsterDb[7].stats.burnDmg = 2;
        this.monsterDb[7].stats.poisonDmg = 0;
        this.monsterDb[7].stats.blindChance = 6;
        this.monsterDb[7].stats.blindPower = 3;

        this.monsterDb.push(new Entity);
        this.monsterDb[7].type = 'monster';
        this.monsterDb[7].behavior = 'aggressive';
        this.monsterDb[7].name = 'Gambling Spirit';
        this.monsterDb[7].cssClass = 'monster-gambling-spirit';
        this.monsterDb[7].stats.maxhp = 5527;
        this.monsterDb[7].stats.baseDmg = 3;
        this.monsterDb[7].stats.armor = 37;
        this.monsterDb[7].stats.evasion = 80;
        this.monsterDb[7].stats.effectsImmunity = 3;
        this.monsterDb[7].stats.piercing = 80;
        this.monsterDb[7].stats.critPower = 120;
        this.monsterDb[7].stats.critChance = 1;
        this.monsterDb[7].stats.burnDmg = 5;
        this.monsterDb[7].stats.poisonDmg = 0;
        this.monsterDb[7].stats.blindChance = 1;
        this.monsterDb[7].stats.blindPower = 35;
        this.monsterDb[7].stats.rootChance = 1;
        this.monsterDb[7].stats.rootPower = 3;

        this.monsterDb.push(new Entity);
        this.monsterDb[8].type = 'monster';
        this.monsterDb[8].behavior = 'aggressive';
        this.monsterDb[8].name = 'Fire Spirit';
        this.monsterDb[8].cssClass = 'monster-fire-spirit';
        this.monsterDb[8].stats.maxhp = 7792;
        this.monsterDb[8].stats.baseDmg = 21;
        this.monsterDb[8].stats.armor = 23;
        this.monsterDb[8].stats.evasion = 10;
        this.monsterDb[8].stats.effectsImmunity = 3;
        this.monsterDb[8].stats.piercing = 0;
        this.monsterDb[8].stats.critPower = 1.4;
        this.monsterDb[8].stats.critChance = 5;
        this.monsterDb[8].stats.burnDmg = 10;
        this.monsterDb[8].stats.poisonDmg = 0;
        this.monsterDb[8].stats.blindChance = 7;
        this.monsterDb[8].stats.blindPower = 4;
        this.monsterDb[8].stats.rootChance = 4;
        this.monsterDb[8].stats.rootPower = 3;

        this.monsterDb.push(new Entity);
        this.monsterDb[9].type = 'monster';
        this.monsterDb[9].behavior = 'aggressive';
        this.monsterDb[9].name = 'Sun Spirit';
        this.monsterDb[9].cssClass = 'monster-sun-spirit';
        this.monsterDb[9].stats.maxhp = 17265;
        this.monsterDb[9].stats.baseDmg = 35;
        this.monsterDb[9].stats.armor = 25;
        this.monsterDb[9].stats.evasion = 20;
        this.monsterDb[9].stats.effectsImmunity = 3;
        this.monsterDb[9].stats.piercing = 5;
        this.monsterDb[9].stats.critPower = 2.1;
        this.monsterDb[9].stats.critChance = 7;
        this.monsterDb[9].stats.burnDmg = 2;
        this.monsterDb[9].stats.poisonDmg = 0;
        this.monsterDb[9].stats.blindChance = 50;
        this.monsterDb[9].stats.blindPower = 4;
        this.monsterDb[9].stats.rootChance = 3;
        this.monsterDb[9].stats.rootPower = 5;

        this.monsterDb.push(new Entity);
        this.monsterDb[10].type = 'monster';
        this.monsterDb[10].behavior = 'aggressive';
        this.monsterDb[10].name = 'Annoying demon';
        this.monsterDb[10].cssClass = 'monster-annoying-demon';
        this.monsterDb[10].stats.maxhp = 922;
        this.monsterDb[10].stats.baseDmg = 6;
        this.monsterDb[10].stats.armor = 13;
        this.monsterDb[10].stats.evasion = 70;
        this.monsterDb[10].stats.effectsImmunity = 5;
        this.monsterDb[10].stats.piercing = 184;
        this.monsterDb[10].stats.critPower = 2.1;
        this.monsterDb[10].stats.critChance = 3;
        this.monsterDb[10].stats.burnDmg = 5;
        this.monsterDb[10].stats.poisonDmg = 2;
        this.monsterDb[10].stats.blindChance = 30;
        this.monsterDb[10].stats.blindPower = 2;
        this.monsterDb[10].stats.rootChance = 2;
        this.monsterDb[10].stats.rootPower = 3;

        this.monsterDb.push(new Entity);
        this.monsterDb[11].type = 'monster';
        this.monsterDb[11].behavior = 'aggressive';
        this.monsterDb[11].name = 'Demon warrior';
        this.monsterDb[11].cssClass = 'monster-demon-warrior';
        this.monsterDb[11].stats.maxhp = 24235;
        this.monsterDb[11].stats.baseDmg = 64;
        this.monsterDb[11].stats.armor = 43;
        this.monsterDb[11].stats.evasion = 10;
        this.monsterDb[11].stats.effectsImmunity = 4;
        this.monsterDb[11].stats.piercing = 24;
        this.monsterDb[11].stats.critPower = 2.4;
        this.monsterDb[11].stats.critChance = 12;
        this.monsterDb[11].stats.burnDmg = 5;
        this.monsterDb[11].stats.poisonDmg = 2;
        this.monsterDb[11].stats.blindChance = 10;
        this.monsterDb[11].stats.blindPower = 3;
        this.monsterDb[11].stats.rootChance = 2;
        this.monsterDb[11].stats.rootPower = 3;

        this.monsterDb.push(new Entity);
        this.monsterDb[12].type = 'monster';
        this.monsterDb[12].behavior = 'aggressive';
        this.monsterDb[12].name = 'Dungeon Ape';
        this.monsterDb[12].cssClass = 'monster-dungeon-ape';
        this.monsterDb[12].stats.maxhp = 46824;
        this.monsterDb[12].stats.baseDmg = 142;
        this.monsterDb[12].stats.armor = 57;
        this.monsterDb[12].stats.evasion = 8;
        this.monsterDb[12].stats.effectsImmunity = 2;
        this.monsterDb[12].stats.piercing = 34;
        this.monsterDb[12].stats.critPower = 2.4;
        this.monsterDb[12].stats.critChance = 12;
        this.monsterDb[12].stats.burnDmg = 2;
        this.monsterDb[12].stats.poisonDmg = 0;
        this.monsterDb[12].stats.blindChance = 10;
        this.monsterDb[12].stats.blindPower = 3;
        this.monsterDb[12].stats.rootChance = 4;
        this.monsterDb[12].stats.rootPower = 2;

        this.monsterDb.push(new Entity);
        this.monsterDb[13].type = 'monster';
        this.monsterDb[13].behavior = 'aggressive';
        this.monsterDb[13].name = 'Aggressive demon dog';
        this.monsterDb[13].cssClass = 'monster-demon-dog';
        this.monsterDb[13].stats.maxhp = 57374;
        this.monsterDb[13].stats.baseDmg = 215;
        this.monsterDb[13].stats.armor = 67;
        this.monsterDb[13].stats.evasion = 15;
        this.monsterDb[13].stats.effectsImmunity = 3;
        this.monsterDb[13].stats.piercing = 54;
        this.monsterDb[13].stats.critPower = 4.4;
        this.monsterDb[13].stats.critChance = 4;
        this.monsterDb[13].stats.burnDmg = 4;
        this.monsterDb[13].stats.poisonDmg = 2;
        this.monsterDb[13].stats.blindChance = 15;
        this.monsterDb[13].stats.blindPower = 3;
        this.monsterDb[13].stats.rootChance = 0;
        this.monsterDb[13].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[14].type = 'monster';
        this.monsterDb[14].behavior = 'aggressive';
        this.monsterDb[14].name = 'Demonic pirate';
        this.monsterDb[14].cssClass = 'monster-demonic-pirate';
        this.monsterDb[14].stats.maxhp = 68554;
        this.monsterDb[14].stats.baseDmg = 225;
        this.monsterDb[14].stats.armor = 85;
        this.monsterDb[14].stats.evasion = 12;
        this.monsterDb[14].stats.effectsImmunity = 5;
        this.monsterDb[14].stats.piercing = 64;
        this.monsterDb[14].stats.critPower = 2.4;
        this.monsterDb[14].stats.critChance = 12;
        this.monsterDb[14].stats.burnDmg = 3;
        this.monsterDb[14].stats.poisonDmg = 0;
        this.monsterDb[14].stats.blindChance = 5;
        this.monsterDb[14].stats.blindPower = 3;
        this.monsterDb[14].stats.rootChance = 0;
        this.monsterDb[14].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[15].type = 'monster';
        this.monsterDb[15].behavior = 'aggressive';
        this.monsterDb[15].name = 'Demonic warlock';
        this.monsterDb[15].cssClass = 'monster-demonic-warlock';
        this.monsterDb[15].stats.maxhp = 128924;
        this.monsterDb[15].stats.baseDmg = 340;
        this.monsterDb[15].stats.armor = 125;
        this.monsterDb[15].stats.evasion = 5;
        this.monsterDb[15].stats.effectsImmunity = 5;
        this.monsterDb[15].stats.piercing = 84;
        this.monsterDb[15].stats.critPower = 1.5;
        this.monsterDb[15].stats.critChance = 16;
        this.monsterDb[15].stats.burnDmg = 2;
        this.monsterDb[15].stats.poisonDmg = 0;
        this.monsterDb[15].stats.blindChance = 4;
        this.monsterDb[15].stats.blindPower = 2;
        this.monsterDb[15].stats.rootChance = 5;
        this.monsterDb[15].stats.rootPower = 2;

        this.monsterDb.push(new Entity);
        this.monsterDb[15].type = 'monster';
        this.monsterDb[15].behavior = 'aggressive';
        this.monsterDb[15].name = 'Furious golem';
        this.monsterDb[15].cssClass = 'monster-furious-golem';
        this.monsterDb[15].stats.maxhp = 131824;
        this.monsterDb[15].stats.baseDmg = 452;
        this.monsterDb[15].stats.armor = 225;
        this.monsterDb[15].stats.evasion = 3;
        this.monsterDb[15].stats.effectsImmunity = 1;
        this.monsterDb[15].stats.piercing = 134;
        this.monsterDb[15].stats.critPower = 3.5;
        this.monsterDb[15].stats.critChance = 10;
        this.monsterDb[15].stats.burnDmg = 5;
        this.monsterDb[15].stats.poisonDmg = 0;
        this.monsterDb[15].stats.blindChance = 4;
        this.monsterDb[15].stats.blindPower = 2;
        this.monsterDb[15].stats.rootChance = 0;
        this.monsterDb[15].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[16].type = 'monster';
        this.monsterDb[16].behavior = 'aggressive';
        this.monsterDb[16].name = 'Golem with shield';
        this.monsterDb[16].cssClass = 'monster-shield-golem';
        this.monsterDb[16].stats.maxhp = 442452;
        this.monsterDb[16].stats.baseDmg = 272;
        this.monsterDb[16].stats.armor = 425;
        this.monsterDb[16].stats.evasion = 10;
        this.monsterDb[16].stats.effectsImmunity = 4;
        this.monsterDb[16].stats.piercing = 12;
        this.monsterDb[16].stats.critPower = 4.5;
        this.monsterDb[16].stats.critChance = 10;
        this.monsterDb[16].stats.burnDmg = 2;
        this.monsterDb[16].stats.poisonDmg = 0;
        this.monsterDb[16].stats.blindChance = 4;
        this.monsterDb[16].stats.blindPower = 2;
        this.monsterDb[16].stats.rootChance = 0;
        this.monsterDb[16].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[17].type = 'monster';
        this.monsterDb[17].behavior = 'aggressive';
        this.monsterDb[17].name = 'Stable fury';
        this.monsterDb[17].cssClass = 'monster-stable-fury';
        this.monsterDb[17].stats.maxhp = 63552;
        this.monsterDb[17].stats.baseDmg = 372;
        this.monsterDb[17].stats.armor = 325;
        this.monsterDb[17].stats.evasion = 15;
        this.monsterDb[17].stats.effectsImmunity = 7;
        this.monsterDb[17].stats.piercing = 32;
        this.monsterDb[17].stats.critPower = 2.5;
        this.monsterDb[17].stats.critChance = 30;
        this.monsterDb[17].stats.burnDmg = 0;
        this.monsterDb[17].stats.poisonDmg = 0;
        this.monsterDb[17].stats.blindChance = 12;
        this.monsterDb[17].stats.blindPower = 3;
        this.monsterDb[17].stats.rootChance = 0;
        this.monsterDb[17].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[18].type = 'monster';
        this.monsterDb[18].behavior = 'aggressive';
        this.monsterDb[18].name = 'Centaur defender';
        this.monsterDb[18].cssClass = 'monster-centaur-defender';
        this.monsterDb[18].stats.maxhp = 79352;
        this.monsterDb[18].stats.baseDmg = 455;
        this.monsterDb[18].stats.armor = 515;
        this.monsterDb[18].stats.evasion = 25;
        this.monsterDb[18].stats.effectsImmunity = 3;
        this.monsterDb[18].stats.piercing = 352;
        this.monsterDb[18].stats.critPower = 3.5;
        this.monsterDb[18].stats.critChance = 30;
        this.monsterDb[18].stats.burnDmg = 2;
        this.monsterDb[18].stats.poisonDmg = 0;
        this.monsterDb[18].stats.blindChance = 5;
        this.monsterDb[18].stats.blindPower = 3;
        this.monsterDb[18].stats.rootChance = 0;
        this.monsterDb[18].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[19].type = 'monster';
        this.monsterDb[19].behavior = 'aggressive';
        this.monsterDb[19].name = 'Centaur berserk';
        this.monsterDb[19].cssClass = 'monster-centaur-berserk';
        this.monsterDb[19].stats.maxhp = 85252;
        this.monsterDb[19].stats.baseDmg = 855;
        this.monsterDb[19].stats.armor = 215;
        this.monsterDb[19].stats.evasion = 7;
        this.monsterDb[19].stats.effectsImmunity = 3;
        this.monsterDb[19].stats.piercing = 852;
        this.monsterDb[19].stats.critPower = 2.5;
        this.monsterDb[19].stats.critChance = 15;
        this.monsterDb[19].stats.burnDmg = 0;
        this.monsterDb[19].stats.poisonDmg = 0;
        this.monsterDb[19].stats.blindChance = 0;
        this.monsterDb[19].stats.blindPower = 0;
        this.monsterDb[19].stats.rootChance = 15;
        this.monsterDb[19].stats.rootPower = 2;

        this.monsterDb.push(new Entity);
        this.monsterDb[20].type = 'monster';
        this.monsterDb[20].behavior = 'scared';
        this.monsterDb[20].name = 'Centaur battle mage';
        this.monsterDb[20].cssClass = 'monster-centaur-battle-mage';
        this.monsterDb[20].stats.maxhp = 121130;
        this.monsterDb[20].stats.baseDmg = 455;
        this.monsterDb[20].stats.armor = 515;
        this.monsterDb[20].stats.evasion = 15;
        this.monsterDb[20].stats.effectsImmunity = 7;
        this.monsterDb[20].stats.piercing = 852;
        this.monsterDb[20].stats.critPower = 3.5;
        this.monsterDb[20].stats.critChance = 24;
        this.monsterDb[20].stats.burnDmg = 2;
        this.monsterDb[20].stats.poisonDmg = 0;
        this.monsterDb[20].stats.blindChance = 0;
        this.monsterDb[20].stats.blindPower = 0;
        this.monsterDb[20].stats.rootChance = 0;
        this.monsterDb[20].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[21].type = 'monster';
        this.monsterDb[21].behavior = 'aggressive';
        this.monsterDb[21].name = 'Centaur Alpha';
        this.monsterDb[21].cssClass = 'monster-centaur-alpha';
        this.monsterDb[21].stats.maxhp = 452000;
        this.monsterDb[21].stats.baseDmg = 1040;
        this.monsterDb[21].stats.armor = 940;
        this.monsterDb[21].stats.evasion = 2;
        this.monsterDb[21].stats.effectsImmunity = 1;
        this.monsterDb[21].stats.piercing = 852;
        this.monsterDb[21].stats.critPower = 4;
        this.monsterDb[21].stats.critChance = 15;
        this.monsterDb[21].stats.burnDmg = 0;
        this.monsterDb[21].stats.poisonDmg = 0;
        this.monsterDb[21].stats.blindChance = 5;
        this.monsterDb[21].stats.blindPower = 3;
        this.monsterDb[21].stats.rootChance = 0;
        this.monsterDb[21].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[22].type = 'monster';
        this.monsterDb[22].behavior = 'scared';
        this.monsterDb[22].name = 'Lesser blood cultist';
        this.monsterDb[22].cssClass = 'monster-lesser-blood-cultist';
        this.monsterDb[22].stats.maxhp = 194512;
        this.monsterDb[22].stats.baseDmg = 1640;
        this.monsterDb[22].stats.armor = 1240;
        this.monsterDb[22].stats.evasion = 7;
        this.monsterDb[22].stats.effectsImmunity = 3;
        this.monsterDb[22].stats.piercing = 1503;
        this.monsterDb[22].stats.critPower = 1.6;
        this.monsterDb[22].stats.critChance = 35;
        this.monsterDb[22].stats.burnDmg = 2;
        this.monsterDb[22].stats.poisonDmg = 2;
        this.monsterDb[22].stats.blindChance = 5;
        this.monsterDb[22].stats.blindPower = 3;
        this.monsterDb[22].stats.rootChance = 0;
        this.monsterDb[22].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[23].type = 'monster';
        this.monsterDb[23].behavior = 'scared';
        this.monsterDb[23].name = 'Higher blood cultist';
        this.monsterDb[23].cssClass = 'monster-higher-blood-cultist';
        this.monsterDb[23].stats.maxhp = 382512;
        this.monsterDb[23].stats.baseDmg = 2740;
        this.monsterDb[23].stats.armor = 2620;
        this.monsterDb[23].stats.evasion = 15;
        this.monsterDb[23].stats.effectsImmunity = 6;
        this.monsterDb[23].stats.piercing = 2103;
        this.monsterDb[23].stats.critPower = 2.4;
        this.monsterDb[23].stats.critChance = 25;
        this.monsterDb[23].stats.burnDmg = 3;
        this.monsterDb[23].stats.poisonDmg = 2;
        this.monsterDb[23].stats.blindChance = 4;
        this.monsterDb[23].stats.blindPower = 2;
        this.monsterDb[23].stats.rootChance = 0;
        this.monsterDb[23].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[24].type = 'monster';
        this.monsterDb[24].behavior = 'scared';
        this.monsterDb[24].name = 'Obsessed blood cultist';
        this.monsterDb[24].cssClass = 'monster-obsessed-blood-cultist';
        this.monsterDb[24].stats.maxhp = 1422100;
        this.monsterDb[24].stats.baseDmg = 3740;
        this.monsterDb[24].stats.armor = 4620;
        this.monsterDb[24].stats.evasion = 5;
        this.monsterDb[24].stats.effectsImmunity = 10;
        this.monsterDb[24].stats.piercing = 4103;
        this.monsterDb[24].stats.critPower = 1.7;
        this.monsterDb[24].stats.critChance = 35;
        this.monsterDb[24].stats.burnDmg = 5;
        this.monsterDb[24].stats.poisonDmg = 0;
        this.monsterDb[24].stats.blindChance = 4;
        this.monsterDb[24].stats.blindPower = 2;
        this.monsterDb[24].stats.rootChance = 0;
        this.monsterDb[24].stats.rootPower = 0;

        this.monsterDb.push(new Entity);
        this.monsterDb[26].type = 'monster';
        this.monsterDb[26].behavior = 'scared';
        this.monsterDb[26].name = 'Blood Cult Leader';
        this.monsterDb[26].cssClass = 'monster-blood-cult-leader';
        this.monsterDb[26].stats.maxhp = 5715250;
        this.monsterDb[26].stats.baseDmg = 5740;
        this.monsterDb[26].stats.armor = 6100;
        this.monsterDb[26].stats.evasion = 15;
        this.monsterDb[26].stats.effectsImmunity = 15;
        this.monsterDb[26].stats.piercing = 7100;
        this.monsterDb[26].stats.critPower = 3.4;
        this.monsterDb[26].stats.critChance = 15;
        this.monsterDb[26].stats.burnDmg = 0;
        this.monsterDb[26].stats.poisonDmg = 6;
        this.monsterDb[26].stats.blindChance = 4;
        this.monsterDb[26].stats.blindPower = 2;
        this.monsterDb[26].stats.rootChance = 0;
        this.monsterDb[26].stats.rootPower = 0;


    }
}

//https://gist.github.com/GeorgeGkas/36f7a7f9a9641c2115a11d58233ebed2
function clone(instance) {
    return Object.assign(
      Object.create(
        // Set the prototype of the new object to the prototype of the instance.
        // Used to allow new object behave like class instance.
        Object.getPrototypeOf(instance),
      ),
      // Prevent shallow copies of nested structures like arrays, etc
      JSON.parse(JSON.stringify(instance)),
    );
}